"""Add deleted field to ClubMember

Revision ID: 39b10ff88b45
Revises: a204609d141c
Create Date: 2022-04-04 15:25:34.639189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b10ff88b45'
down_revision = 'a204609d141c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_member', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_member', 'deleted')
    # ### end Alembic commands ###
