"""Make club_member.name unique

Revision ID: c0662f6d9342
Revises: b2af90f02e6c
Create Date: 2022-04-22 16:17:16.465796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0662f6d9342'
down_revision = 'b2af90f02e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'club_member', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club_member', type_='unique')
    # ### end Alembic commands ###
