"""Add total_earnings field to club members

Revision ID: e303696829e5
Revises: c0662f6d9342
Create Date: 2022-07-30 11:52:32.118221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e303696829e5'
down_revision = 'c0662f6d9342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_member', sa.Column('total_earnings', sa.Integer()))
    # ### end Alembic commands ###
    op.execute("UPDATE club_member SET total_earnings=nickels; ")
    op.alter_column('club_member', 'total_earnings', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_member', 'total_earnings')
    # ### end Alembic commands ###
